apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmaster-deployment
spec:
  selector:
    matchLabels:
      app: taskmaster
  replicas: 3
  template:
    metadata:
      labels:
        app: taskmaster
    spec:
      containers:
        - name: taskmaster
          image: sachintech/taskmaster:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: taskmaster-ssvc
  annotations:
    # Annotation for AWS ALB Ingress Controller
    alb.ingress.kubernetes.io/scheme: internet-facing # Specify if the ALB should be internet-facing or internal
spec:
  selector:
    app: taskmaster
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
