apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: taskmaster-deployment
spec:
  selector:
    matchLabels:
      app: taskmaster
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: taskmaster
    spec:
      containers:
        - name: taskmaster
          image: sachintech/taskmaster:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service
metadata:
  name: taskmaster-ssvc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:{region}:{user id}:certificate/{id}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: taskmaster
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
  type: LoadBalancer
