apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: taskmaster-deployment
spec:
  selector:
    matchLabels:
      app: taskmaster
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: taskmaster
    spec:
      containers:
        - name: taskmaster
          image: sachintech/taskmaster:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

apiVersion: v1
kind: Service
metadata:
  name: taskmaster-ssvc
  namespace: webapps
spec:
  selector:
    app: taskmaster
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmaster-ingress
  namespace: webapps
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:330859521773:certificate/31ec9df6-5b5e-45bf-aa9d-68f65159697a
spec:
  rules:
    - host: taskadmin.technical-journey.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskmaster-ssvc
                port:
                  number: 80

